Replace isDisabled prop with media feature query
harvard-lil/perma pull request #3579
Opened 2024-07-25 15:28 UTC by tinykite

## What this does 
This is a small quality-of-life improvement for the way the `Spinner` component currently functions. I previously added an `isDisabled` prop to the `Spinner` component so that the loading animation it typically displays can be disabled on a case-by-case basis. 

This update takes advantage of the `usePreferredReducedMotion` composable from the vue-use library to disable the `Spinner` based on if a user has toggled an OS-level setting to reduce or disable motion. For me personally, that means I can do work related to user uploads and captures without having to repeatedly manually disable the component. 

## Definition of done 
- The spinner should display "Loading" based on the value of the `prefers-reduced-motion` query. 
- This is not intended to meet the success criteria of [WCAG SC 2.2.2: Pause, Stop, Hide](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html), which could be addressed with a future redesign. 

## Screenshot 
Instead of a loading animation, the component will simply display the word "loading". 
<img width="1728" alt="Screenshot 2024-07-25 at 9 45 31 AM" src="https://github.com/user-attachments/assets/fa9dd73e-ae59-4e3d-8240-090464ab0bb0">

## Linear issue 
Satisfies Linear issue ENG-1001.  

## How to test 
- On Mac OS X, a user can indicate a preference for reduced motion in System Settings, by navigating to System Settings > Accessibility > Display > Reduce motion. Toggle this flag and try to create a single capture — you should see the text "Loading".
  - Note: The labelling of this is specific to Mac OS. On Android, for example, the option is labeled "Remove animations." The [MDN web docs entry on prefers-reduced-motion](In macOS: System Preferences > Accessibility > Display > Reduce motion.) provides a much more complete, cross-platform list of how to toggle the flag. 
- If you don't see the "Loading" text — and a capture simply immediately succeeds — this is almost certainly due to your local Docker config. I can double-check what you'd need to toggle to see loading states.

2024-07-30 18:16 UTC, cmsetzer requested changes
Hi @tinykite, I am seeing the "Loading" text (no animated spinner) regardless of whether Reduce Motion is active. After some digging, it appears `showLoader` always evaluates to false regardless of Reduce Motion:

![image](https://github.com/user-attachments/assets/04f1acae-08c4-476c-96a7-5a32ec5404e1)

From what I can tell, `usePreferredReducedMotion()` is not returning a string as expected (e.g. `'no-preference'`). But I can't tell why — looks like you're using `usePreferredReduceMotion` correctly. Any ideas?

2024-07-31 15:29 UTC, tinykite commented
> Hi @tinykite, I am seeing the "Loading" text (no animated spinner) regardless of whether Reduce Motion is active. After some digging, it appears `showLoader` always evaluates to false regardless of Reduce Motion:
> 
> ![image](https://private-user-images.githubusercontent.com/37311998/353568825-04f1acae-08c4-476c-96a7-5a32ec5404e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Mzk0NjEsIm5iZiI6MTcyMjQzOTE2MSwicGF0aCI6Ii8zNzMxMTk5OC8zNTM1Njg4MjUtMDRmMWFjYWUtMDhjNC00NzZjLTk2YTctNWEzMmVjNTQwNGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjYzYWU4NWYzMGM0NjkwNTI3OWYzNWEzMmM1MzM2NWU5ZWZkMTFjZDNiMWEwOTQ5OWNmMzA4M2YwNjIzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1iEvneUdnU6z56XbzROfL2W03ci53JmJW6XQ_c7U4w)
> 
> From what I can tell, `usePreferredReducedMotion()` is not returning a string as expected (e.g. `'no-preference'`). But I can't tell why — looks like you're using `usePreferredReduceMotion` correctly. Any ideas?

Ah, great catch! I had thought I had conclusively tested this, but this was definitely a mistake on my part. 

So, the `vue-use` docs provide this example for how the return value from the composable can be used: 

```
<template>
  <UsePreferredReducedMotion v-slot="{ motion }">
    Preferred Reduced Motion: {{ motion }}
  </UsePreferredReducedMotion>
</template>
```

This is definitely correct. But something that's _really_ easy for me to forget, as someone fairly new to Vue, is that you can directly reference `motion` in this example, within the `template` blocks, as developer convenience. 

Outside of the `template` block, eg within your own JavaScript code, you need to refer to the value the `usePreferredMotion` composable returns in the same way you'd refer to a reactive `ref`. So instead of this: 

```
const showLoader = motionPreferences === 'no-preference'
```

I should have written this: 
```
const showLoader = motionPreferences.value === 'no-preference'
```

I made a fix for this in [9fcec7f](https://github.com/harvard-lil/perma/pull/3579/commits/9fcec7ffb3400204c9ec2a5d3563701bfff00259).

2024-07-31 19:10 UTC, cmsetzer approved these changes
Working great now. Thanks for the fix and the explanation!

2024-08-01 14:19 UTC, rebeccacremona commented
I'm be bold and hit the merge button on @tinykite's behalf 🤝

2024-08-01 14:19 UTC, merged