Save user uploads as WACZs
harvard-lil/perma pull request #3679
Opened 2024-12-16 15:11 UTC by bensteinberg

This is a first cut at preserving user uploads as WACZ files rather than WARCs. I'm not sure which Linear ticket is the best one to link here. I'm making this a draft for now.

This works, in the sense that it produces a valid WACZ that replayweb.page can play back, but it does not yet play back in Perma; the error message, from wabac.js. is e.g.

```
Archived Page Not Found

Sorry, this page was not found in this archive:

file:///8MXD-LZ6V/upload.jpg?version=040666551871161394
...
```

I'm guessing I need a slightly different set of options to py-wacz.

2024-12-16 16:02 UTC, bensteinberg commented
Apart from getting this to work, the main question is what the metadata should look like.

2024-12-16 19:33 UTC, bensteinberg commented
I think the problem here is that the CDX index is broken, because the entries for `file:///` URIs are getting rewritten to reduce consecutive slashes to one; I think this is down to [cdxj_indexer just using `surt` on the URL](https://github.com/webrecorder/cdxj-indexer/blob/9ad2b9e1c54d2d20c391050fdb831ca1ee981504/cdxj_indexer/main.py#L301-L305), rather than doing [what warcio does with `getSurt()`](https://github.com/webrecorder/warcio.js/blob/71e4fdd03b4fefb4849f3d8a7449118a33730579/src/lib/utils.ts#L33-L35), in the Scoop context:
```
    if (!url.startsWith("https:") && !url.startsWith("http:")) {
      return url;
    }
```
I'm going to see if I can demonstrate this. If this is the problem, I'm not sure where to make a fix.

2025-01-06 17:35 UTC, rebeccacremona commented
(A possible thread to pull when working further with this: does using a `response` type record instead of a `resource` record affect the indexing? It shouldn't, in theory... but, since I recall that in Scoop-produced WARCs, everything is a response record, including attachments like the screenshot, provenance summary, etc., and I do not know why, I am a little suspicious this could be related.)

2025-01-06 21:25 UTC, bensteinberg commented
Thanks. I've tried with both response and resource records; not sure it matters here. (Philosophically, these might better be resource records.) I've removed the dependency on the indexer and am now creating the WACZ inline. I'm still not producing a working file, but I've pushed the changes for now.

2025-01-06 21:33 UTC, bensteinberg commented
The thread I'm pulling now is that replayweb claims "2 hashes verified, 1 invalid" -- but I haven't been able to find an invalid hash. I am not perfectly confident in the way I'm calculating offset in the WARC, which I suppose could be the problem.

2025-01-06 21:58 UTC, rebeccacremona commented
I can try and find the code we used to use for making CDXlines, back when that was a function of Perma. Those were not CDXJ, but it could be interesting just to see.

2025-01-06 22:27 UTC, bensteinberg commented
One of my thoughts here is that since what we are trying to do is so minimal, there's no need for a general solution to indexing or any other part of WACZ production.

2025-01-07 21:19 UTC, bensteinberg commented
Thanks @rebeccacremona and @matteocargnelutti for the help!

> replayweb claims "2 hashes verified, 1 invalid"

(This is true for working WACZs.)

Is it worth adding the WARC header REFERS_TO_TARGET_URI?

2025-01-08 15:48 UTC, rebeccacremona requested changes
Thanks so much for taking this on!! This is cool!

I read through your code once so far; I'd love to take a more detailed look later, including looking at a couple of the finished WACZs. But in the meantime, shared a few thoughts.

> replayweb claims "2 hashes verified, 1 invalid"
> (This is true for working WACZs.)

Hmmm, interesting. I wonder if this is true just for these new WACZs or for other WACZs we produce... Maybe let's dig.

> Is it worth adding the WARC header REFERS_TO_TARGET_URI?

Interesting. TBD!

2025-01-08 15:48 UTC, rebeccacremona commented on perma_web/api/tests/test_link_authorization.py
> +        self.assertTrue(self.link.wacz_size)
I think this test needs further changes, with this new setup, to prove that the patch worked. Before, demonstrating that once there was a WACZ and now there is a WARC demonstrated that the process succeeded. Now, just asserting that warc_size is still zero and wacz_size is still non-zero doesn't, I think, assert much.

Instead, I think it would be more meaningful to a) check for the presence of a new `Capture` object with `role='provenance_summary'` (more on that below) and b) assert that the wacz_size is different than what it was before. That still doesn't assert anything about the contents of the WACZ (easier to test an upload-your-own playback in our functional tests), but I think that might be more complete?

2025-01-08 15:48 UTC, rebeccacremona commented on perma_web/api/tests/test_link_resource.py
> +            self.assertRecordsInArchive(link, upload=True, filetype='wacz')
With this change, I suspect that having `filetype` as a parameter of `assertRecordsInArchive` is now unnecessary, and that the filetype is now always wacz, and that whole branch can be removed. Do you agree?

2025-01-08 15:48 UTC, rebeccacremona commented on perma_web/perma/templates/provenance-summary.html
> +      </header>
Hooray for a provenance summary!

TBD! I think probably let's add some more details here before this goes live?

2025-01-08 15:48 UTC, rebeccacremona commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
`# version?`

Hmmm... 

So if we wanted to consider the production "tag" the version, then we'd have to somehow expose that to the application and interpolate here... Which sounds like a bit of a pain in the butt? (Some salt state that runs a command that gets the current tag and puts it into an ENV var, and then an application setting that reads that ENV var?)

Some new version that we just increment if/when we change this code (we'll be prone to forget, I imagine).

Or skip entirely?

Hmmmmmmmmm.

2025-01-08 15:48 UTC, rebeccacremona commented on perma_web/perma/models.py
>                            url=warc_url)
We'll want to make another `Capture` object here, with `role='provenance_summary'`, to go along with the primary.

See also the discussion about whether, at this time, we should remove the random string appended to the end. If we are going to do that, I think we should do it now rather than later, make the corpus more consistent.

2025-01-08 15:57 UTC, bensteinberg commented on perma_web/api/tests/test_link_authorization.py
> +        self.assertTrue(self.link.wacz_size)
Yeah, sounds good -- let me see about adding and checking a new `Capture` object.

2025-01-08 16:00 UTC, bensteinberg commented on perma_web/perma/templates/provenance-summary.html
> +      </header>
What details do you have in mind? This is minimal partly because it's a placeholder and opportunity for discussion, but also because I'm inclined to keep the file as short as possible. I don't think it's necessary to provide the level of provenance detail Scoop provides.

2025-01-08 16:12 UTC, bensteinberg commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
Yeah, the automated mechanism for accomplishing this would be slightly baroque and the manual way would be failure-prone. I think I still want to add it? Let me think about the best approach -- I think it will be something like what you describe, maybe writing settings directly rather than using an env var.

2025-01-08 16:14 UTC, bensteinberg commented on perma_web/perma/models.py
>                            url=warc_url)
> the discussion about whether, at this time, we should remove the random string appended to the end

I haven't seen this discussion yet -- is it a comment on this PR, or elsewhere?

2025-01-08 16:20 UTC, bensteinberg commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
If we do set this up, should the setting be visible in templates? Would we want to expose it elsewhere in the application?

2025-01-08 17:06 UTC, bensteinberg commented
> > replayweb claims "2 hashes verified, 1 invalid"
> > (This is true for working WACZs.)
> 
> Hmmm, interesting. I wonder if this is true just for these new WACZs or for other WACZs we produce... Maybe let's dig.

This is true for freshly-created Perma WACZs made with Scoop.

2025-01-08 17:51 UTC, rebeccacremona commented on perma_web/perma/templates/provenance-summary.html
> +      </header>
>  I don't think it's necessary to provide the level of provenance detail Scoop provides.

Agreed.

How about time of original capture (if any), time of replacement, replacement mime type?

2025-01-08 17:53 UTC, rebeccacremona commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
I don't know why I feel like we did this once before, or something like it, and it was exposed in the templates, and it was read by an LIL service or uptimerobot or something....

2025-01-08 17:54 UTC, rebeccacremona commented on perma_web/perma/models.py
>                            url=warc_url)
It is probably in the Liner ticket for studying and designing this. I'll try and Slack you a link.

2025-01-08 17:56 UTC, rebeccacremona commented on perma_web/api/tests/test_link_authorization.py
> +        self.assertTrue(Capture.objects.filter(link_id=self.link.pk, role='provenance_summary').exclude(pk=old_primary_capture.pk).exists())
Thanks for adding this! I think you don't need the `.exclude(pk=old_primary_capture.pk` in this one; that won't be caught by this query anyway.

2025-01-08 18:01 UTC, rebeccacremona commented on perma_web/perma/models.py
> +            user_upload='True',
Ooh, this is a fun question: should `user_upload` be true on the provenance summary, since we are creating it? I can see it going either way.

I also observe that, in the primary capture, we have long been passing in the string `'True'` and not a python boolean `True`. This is a Boolean field. I... wonder what we have in the DB... I will check... Hopefully it is converting to a Boolean, but either way, oops....

2025-01-08 18:10 UTC, rebeccacremona commented on perma_web/perma/models.py
> +            user_upload='True',
Okay locally, looks like these are converted to Booleans:
```
In [4]: for capture in Capture.objects.filter(user_upload=True):
   ...:     print(type(capture.user_upload))
   ...: 
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>

In [5]: for capture in Capture.objects.filter(user_upload='True'):
   ...:     print(type(capture.user_upload))
   ...: 
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
```

That is... not a thing I would have expected to happen implicitly.

In any case, how about we switch to passing in `True`?

2025-01-08 18:30 UTC, bensteinberg commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
Here's how we did it before: https://github.com/harvard-lil/perma/commit/7e0a04b0403e9d44b95ce411fd6e6b86216099d1

2025-01-08 18:34 UTC, bensteinberg commented on perma_web/perma/templates/provenance-summary.html
> +      </header>
See [63ca218](https://github.com/harvard-lil/perma/pull/3679/commits/63ca21885e5dbb5ca8aee6b232a230baedaa55c9) -- 

![image](https://github.com/user-attachments/assets/e5e462be-cd28-4681-beaa-0f95346f2940)

2025-01-08 18:36 UTC, bensteinberg commented on perma_web/perma/models.py
> +            user_upload='True',
I was wondering about that setting for the provenance; I'll switch that one to `False` and change the other from string to boolean.

2025-01-08 18:39 UTC, bensteinberg commented on perma_web/perma/models.py
> +            user_upload='True',
Done in [44191e7](https://github.com/harvard-lil/perma/pull/3679/commits/44191e7719a4947ed8d1d473474e45e87959ea98)

2025-01-08 18:42 UTC, bensteinberg commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
Now see [e7d9405](https://github.com/harvard-lil/perma/pull/3679/commits/e7d94053df8da3d1c5b1004ee49c066179f3d19d) -- I haven't yet set up the mechanism for interpolation in deployment.

2025-01-08 18:52 UTC, rebeccacremona commented on perma_web/perma/templates/provenance-summary.html
> +      </header>
Looks good to me!

2025-01-08 18:58 UTC, rebeccacremona approved these changes

2025-01-08 21:18 UTC, bensteinberg commented on perma_web/perma/utils.py
> +            "software": "Perma.cc",  # version?
I now have a mechanism for interpolation in deployment; I don't love it, but it works, and I may revisit it later.

2025-01-09 14:53 UTC, merged